### ISSUE TITLE
jwt_secret and other potentially sensitive info queryable

### ISSUE THREAD

**Issue by kane-mason** [thomas4019/expressa#102]
im just wondering, should the jwt token be visible in the admin panel. if its visible in the admin panel that means it is available through the settings collection request... im just thinking, you might give other users permission to log into to admin to do mundain data correction etc on users, you wouldn't necessarilly want them to view these settings!

im sure we could chnge the admin role permissions to `settings: {operation}: false`, but is this the best way?

**Comment by thomas4019** [comment]
This was fixed with the `view server details` and  'settings: view/edit' permissions. It's required to get the details on the main admin panel.
