### ISSUE TITLE
Cleared Fields Do Not Update

### ISSUE THREAD

**Issue by kane-mason** [thomas4019/expressa#104]
So the scenario i ran into was, i added a description a field in the users schema. But later decided i didn't want it, so i went into admin panel to clear it, but unfortunately when saving, the cleared value does not make its way back into the filesystem. 

I appreciate this might be a tricky one, and is not very urgent in my case. But im just thinking will this become a problem when clearing other fields, for example in a user document, like password or any field really

**Comment by thomas4019** [comment]
Good find, I think this is particular to how I added descriptions. I just pushed a new version to `json-schema-editor` that should fix it :)

**Comment by kane-mason** [comment]
ok confirmed it works!

**Comment by kane-mason** [comment]
Erm this works in the repo but not when installed via npm, think you need to bump version and/or rebuild admin module ?

**Comment by thomas4019** [comment]
Ahh, thanks! Yep, I just bumped the version and released so it should be publicly available now.

**Comment by kane-mason** [comment]
sorted, thanks
