### ISSUE TITLE
Error in Console

### ISSUE THREAD

**Issue by kane-mason** [thomas4019/expressa#105]
When you have a field that contains `links` as detailed in `relationships.md`, and try to create a document for that collection via the admin panel, there is the following console error

![image](https://user-images.githubusercontent.com/23186829/90966077-a2908e80-e4ce-11ea-9911-43b092537083.png)

schema:

![image](https://user-images.githubusercontent.com/23186829/90966085-b0461400-e4ce-11ea-96a9-845aa6c7779a.png)

also is there a way to add these links via admin panel?

**Comment by thomas4019** [comment]
Ahh, yeah, this error is strange one. It's not possible to add via the admin panel, but that's definitely on the roadmap since it's very useful.

**Comment by kane-mason** [comment]
so this is as a result of the spaces in the class string - if you change the class value to just `"comment-link"` it works

**Comment by kane-mason** [comment]
definitely not a biggie but if this layout could be addressed too please :)

![image](https://user-images.githubusercontent.com/23186829/91220400-65b9d700-e71c-11ea-85a1-d808e9a62d14.png)

Oh and clicking on the link opens a new tab, is that intentional?

**Comment by thomas4019** [comment]
Just moved the link up a bit as suggested in the current release. The open in new tab was intentional for racepass specifically. It can be controlled just by not putting in the `open-in-modal` class name there though so it's easy to customize.

**Comment by kane-mason** [comment]
fixed
