### ISSUE TITLE
Permissions Vulnerability

### ISSUE THREAD

**Issue by kane-mason** [thomas4019/expressa#107]
Quite a serious one. It seems as soon as you add `&page=` to a database query, you do not need to satisfy any permission requirements!

Try on the `users` collection, do not set an access token, make sure `Anonymous` and `Authenticated` roles do not have `users: view` permissions: `users?limit=10&page=1` it will return a full page filled with user information :/

If you remove `&page=1` as such, `users?limit=10` and it will return `[]` (which is still technically wrong, you should get a permissions error, but better than a list)

Same thing happens for any collection,

**Comment by thomas4019** [comment]
Eeeek, great find! I'm glad you found this as it really is a bad vulnerability. Fixed in the latest release.

The reason it returns `[]` is that access control is done on an individual document level and in theory a listener could let someone access just a single document in a collection.
