### ISSUE TITLE
Body Parser Limit

### ISSUE THREAD

**Issue by kane-mason** [thomas4019/expressa#111]
[Body Parser](https://www.npmjs.com/package/body-parser) auto imposes a 100kb limit for request payloads. This is somewhat limiting if you need to upload image data in the json payload. 

The ability to set this max yourself would be cool, possibly in the development.json? I get and see the need to set a limit, it would be even better if we could configure the limit per route, and even better better configure the max for specifix properties in the json, but not sure how feasible this is

**Comment by thomas4019** [comment]
I added the option to set a global limit as a new setting since that does seem useful. It's not possible for specific properties in the json without doing lots of manual work since that's not a common approach. Setting a different limit per route should be possible, but isn't trivial
