### ISSUE TITLE
Store settings JSON alphabetically for cleaner diffs

### ISSUE THREAD

**Issue by kane-mason** [thomas4019/expressa#113]
When updating settings **schema** from the admin panel, the default properties seem to get wiped out

![image](https://user-images.githubusercontent.com/23186829/92788795-89328200-f3aa-11ea-80d6-dce7528ce125.png)

This is less of a problem but still can get tiresome, the properties also get rearranged causing unnecessary diffs

![image](https://user-images.githubusercontent.com/23186829/92789119-d1ea3b00-f3aa-11ea-9bac-3c6d772c491b.png)

**Comment by kane-mason** [comment]
That second issue seems to happen pretty much anywhere when data is updated. perhaps sorting object keys before persiting could prevent it? Found this https://stackoverflow.com/questions/24629917/sorting-javascript-object-by-key-value-recursively

**Comment by thomas4019** [comment]
Great idea! I've changed the file implementation to sort objects by key as you've suggested :)
