### ISSUE TITLE
Permission 'delete own' does not work on collections other than 'user'

### ISSUE THREAD

**Issue by kane-mason** [thomas4019/expressa#120]
As the title describes. Trying to delete your own document in a collection other than users will fail with permissions error. I narrowed this down to the `collectionPermissionCheck` listener where it does not properly cater for deletingOwn since a delete command does not trigger a full retrival of the document to be deleted

**Comment by thomas4019** [comment]
Great find! I changed the delete endpoint to load the document since that will make it work. Bug is fixed in latest version 0.5.15
