### ISSUE TITLE
Log error message in request log

### ISSUE THREAD

**Issue by kane-mason** [thomas4019/expressa#121]
Since expressa wraps all errors and appends a message. It should be possible to always log the `message` too to the `request_log`? 

I think it would be useful if you exposed some of the expressa utils to the consumer such `ApiError` so that the consumer can throw errors in the same way expressa does and they get logged consistenly.

Other useful utils to expose to consumer include 
`generateDocumentId` - if you need to create records and want to ensure same uuid mechanism as expressa 
`createSecureRandomId`
`doLogin` - for custom (like social) login routing

**Comment by thomas4019** [comment]
I totally agree that these things should be exported as that does seem useful. With regard to logging the message, I think that's a great idea too. Usually I think it's best not to log the response, but for error messages I think that would be very helpful.

**Comment by thomas4019** [comment]
Fixed in `0.5.26`

**Comment by kane-mason** [comment]
This seems to have stopped working!

**Comment by kane-mason** [comment]
Ok it seems the message is being logged, but is not displayed in the admin panel

**Comment by thomas4019** [comment]
Good catch! I just fixed this  in version 1.0.1. Let me know if you see any issues.
