### ISSUE TITLE
A way to return specific fields in document

### ISSUE THREAD

**Issue by kane-mason** [thomas4019/expressa#125]
Sometimes you dont want the server to return the entire document. Mongo has Project Fields to return from Query (https://docs.mongodb.com/manual/tutorial/project-fields-from-query-results/) would be nice to have this feature.

Like we use the the `query={}`
We could maybe have something like `fields={name: 1, meta.created: 1}`  etc

**Comment by thomas4019** [comment]
I totally agree that this would be a nice feature and I don't think it would be too much work actually since [mongo-query-to-postgres-jsonb](https://github.com/thomas4019/mongo-query-to-postgres-jsonb) already supports projections. I'll likely be able to add in a week or two.

**Comment by thomas4019** [comment]
Feature was added to the latest version with support for all database types :)

**Comment by kane-mason** [comment]
awesome thanks!

**Comment by kane-mason** [comment]
So this is working very nicely for the usual field. But projection into arrays does not work.

for example if i have a doc

```js
        {
            "name": "Test",
            "sport": "running",
            "events": [
                {
                    "name": "whatever",
                    "cost": 150
                },
                {
                    "name": "whatever-nexr",
                    "cost": 180
                }
            ],
            "source": "internal",
        }
```

then i using `fields={ "events.cost": 1 }` returns the wrong information

**Comment by thomas4019** [comment]
Thanks for pointing out that limitation. The latest release now supports arrays too :)
