### ISSUE TITLE
Complex sort

### ISSUE THREAD

**Issue by kane-mason** [thomas4019/expressa#126]
I initially thought, allow the other db types to use the various mongo sorting methods, such as https://stackoverflow.com/questions/27224225/how-can-i-sort-mongodb-regex-search-query-results-based-on-regex-match-count

That is prob the right way, but that may require lots of work - so then i thought maybe a listener which gives you a chance to manipulate the list of documents before sending back to client

**Comment by kane-mason** [comment]
after digging a bit, i discovered the undocumented `getpresend` listener, would you recommend i use it for this case?

**Comment by kane-mason** [comment]
Ok, while was i wanted can be somewhat achieved, unfortunately a lot of the results i need are already truncated by the page or limit - i would need the sort/orberby to happen on the db

**Comment by thomas4019** [comment]
Yep, `getpresend` listener would be good, but like you've discovered it only really makes sense when there's no pagination. My recommendation here, would be for you to create a new simple column that you can sort on. Even if we did add some complex sort feature, the performance of it probably wouldn't be good. So for simplicity an efficiency I don't think this makes sense adding. Please reopen if you disagree.
