### ISSUE TITLE
Postgres jsonb Mongo query search arrays

### ISSUE THREAD

**Issue by kane-mason** [thomas4019/expressa#127]
Following an offline discussion with @thomas4019 - when storage type is postrgresql, mongo search queries do not support searching within arrays.

Apparently this is already implemented in `mongo-query-to-postgres-jsonb` and `expressa` just needs to be updated to make use of the feature properly

**Comment by thomas4019** [comment]
Feature added in latest release. Note: searching arrays within arrays is not yet supported since that adds a lot of complexity and isn't supported by `mongo-query-to-postgres-jsonb`.
