### ISSUE TITLE
Bug with Array Projection

### ISSUE THREAD

**Issue by kane-mason** [thomas4019/expressa#129]
So retrieving specific fields within an array seems to be working like a charm now, however if you want to retrieve the entire value/object in the array a `null` result is returned. See example below, cities is an array of strings, sports is an array of objects - i have just requested the entire arrays (not specific properties within)

![image](https://user-images.githubusercontent.com/23186829/99916348-79241080-2d12-11eb-9a0d-085539c792cc.png)

Example of what i would expect:

![image](https://user-images.githubusercontent.com/23186829/99916490-226b0680-2d13-11eb-81c8-67d63a79e51d.png)

**Comment by thomas4019** [comment]
This was fixed in the latest version of `mongo-query-to-postgres-jsonb` so doing another `npm install` should fix this now.
