### ISSUE TITLE
Bulk Operations

### ISSUE THREAD

**Issue by kane-mason** [thomas4019/expressa#134]
Update the db layer for more efficient handling of bulk operations and useage of mongo query.

For example, lets say i wanted to create a scheduled task that once a day checks if the records in a collection are now in the past, and update their `status` from `active` to `completed`. The api.db layer only allows for update calls on a single document, and it would be inefficient to iterate through all the docs and update one by one. 

What i thought was a new `updateMany` (or something) function for each of the dbs. And it works similar to `find` where you have more fine grained control over which fields you update. It would create a single query to update many ids (or fields that match something), and update only the field in question, for example `status` from above

This is not necessarilly useful for an endpoint, but more a backend administrative feature. Alternatively one could create the more complex `jsonb` queries on the db itself or even in the node application, but expressa has already done such a great job of shielding the consumer of the mongo-postgres jsonb conversion it would be great and neat if it could also in this case!

**Comment by thomas4019** [comment]
I like the idea of an `updateMany`. I think it could take in a query and the mongo-style update parameters. The postgres support should be pretty straightforward since my library supports these kinds of queries too. I can add this in within a few weeks if it's helpful.

**Comment by kane-mason** [comment]
it would help me for sure! Just not sure about the name `updateMany`, maybe `updateComplex` or something

**Comment by thomas4019** [comment]
updateWithQuery released in version 0.5.25. I may expose an endpoint with it sometime, but for now it's available at the database level.
