### ISSUE TITLE
update with query

### ISSUE THREAD

**Issue by kane-mason** [thomas4019/expressa#137]
this is similar to my other logged [issue](https://github.com/thomas4019/expressa/issues/134), but for single doc updates. Currently the `rawQuery` does not get passed to the `db` layer. Meaning if we want to make updates to the doc using a mongo query, we have no choice but to do it via the `/update` endpoint and not using `api.db[collection].update`, which is of course quite limiting on the server side, performing a http request is more of a hack, and if we use the `db` api then it requires retrieving the entire doc in order to make a small update to it. This may not mean updating `update` on the db layer, because `updateById` in `collections.js` depends on it how it is (though maybe there is an inefficency that could be improved on), so potentially creating an additional `updateWithQuery` or something, simlar to how `find` works

**Comment by thomas4019** [comment]
updateWithQuery released in version 0.5.25
