### ISSUE TITLE
Property Type Any

### ISSUE THREAD

**Issue by kane-mason** [thomas4019/expressa#139]
What is the best way to specify a properties that has any or multiple possible types?

According to http://json-schema.org/understanding-json-schema/reference/type.html i can just specify an array like `type: ["string", "number", "object", "array", "boolean", "null"]` - while something like this seems to work, i dont think its supported by the admin panel. Not that its super important it, it should just not error.

Is there another way? Maybe leaving out the `type` property all together and it can skip validation?

**Comment by thomas4019** [comment]
I didn't know you could specify multiple types, that's good to know! In the short term, we could add a type "mixed" which lets it be any type. Long term I'd like a better solution, but multi-selection is non-trivial. I'm also thinking about maybe adding support for [oneOf](https://json-schema.org/understanding-json-schema/reference/combining.html#oneof) which could also solve this problem..

**Comment by kane-mason** [comment]
Mmm i think "mixed" or "any" (thinking of Typescript) is good and is an easy fit in admin panel etc. Long term oneOf is a nice solution but would need to fit neatly into admin panel, but not urgent cause haven't had a lot of use cases personally other than this

**Comment by thomas4019** [comment]
I added an "any" type (I like the TypeScript reference) and published it with version 0.5.24"
