### ISSUE TITLE
Admin Panel - Display Error Message

### ISSUE THREAD

**Issue by kane-mason** [thomas4019/expressa#143]
Along with the error code it would be nice to show the error message as a toast over the screen,

We have non technical people doing data capturing and they dont really know how to use dev tools etc to retrieve error message.

In addition:
1. The message should remain until dismissed, giving them a chance to read it properly. 
2. Errors generated from validation (`ajv` i think) are not very readable as just strings, some formatting to display these nicely would be great
3. `ajv` is many majjor versions behind, updgrade to latest could be nice

**Comment by thomas4019** [comment]
Good idea. I've updated `ajv` to the latest version and improved the error message and made it persist until closed.
