### ISSUE TITLE
Admin - Use Fields for Collection List

### ISSUE THREAD

**Issue by kane-mason** [thomas4019/expressa#147]
When clicking on a particular collection in the `data` menu, a request is made for all the records for a particular page.

Since the entire record is requested this results in quite a large payload (depending on the collection) for example:

![image](https://user-images.githubusercontent.com/23186829/114324053-6e82e000-9b28-11eb-9479-955d6edf0b09.png)

Since we only require the the fields for the columns we display, we could add the `fields={_id:1, name:1, start_location:1, end_location:1 }` to speed this up

![image](https://user-images.githubusercontent.com/23186829/114324082-91ad8f80-9b28-11eb-97c1-0f42fcb7e3e6.png)

**Comment by thomas4019** [comment]
I like this idea. I think it mostly makes sense when the collection has specific columns specified, otherwise the admin tool shows all the columns I think so it wouldn't help then.

**Comment by kane-mason** [comment]
Yeah for specific columns. Most collections will specify columns too because otherwise the view is quite cluttered

**Comment by thomas4019** [comment]
This change was done in version 1.0.1. Let me know if you see any issues.
