### ISSUE TITLE
Mongo Projection

### ISSUE THREAD

**Issue by kane-mason** [thomas4019/expressa#171]
I noticed in `db/mongo.js` that `fields` gets passed to the `find` and `get` mongo db commands, however according to mongo [docs](https://docs.mongodb.com/drivers/node/current/usage-examples/find/) it expects `projections` property to limit fields?

**Comment by kane-mason** [comment]
im busy working in this area so can update it, but just wondering if i am missing something?

**Comment by thomas4019** [comment]
Also, make sure to run `npm run testdbs` when doing these kinds of changes (that command needs local docker to be setup)

**Comment by kane-mason** [comment]
Fixed here https://github.com/thomas4019/expressa/pull/172

I struggled with `docker` and `npm run testdbs`. However i did manage to run both `mongo` and `postgres` tests separately and all passed
