### ISSUE TITLE
updateWithQuery error

### ISSUE THREAD

**Issue by kane-mason** [thomas4019/expressa#177]
The `postgres` implementation of `updateWithQuery` throws an error if no update was done, but the other databases do not.. Is there a reason for this? WOuld you mind if i just returned `matchedCount: 0` ?

**Comment by thomas4019** [comment]
Good catch! Yeah, I don't see any need for the special case. Removing the if and throw in the postgres section seems good to me

**Comment by kane-mason** [comment]
K i will make the change
