### ISSUE TITLE
updating _id doesnt update id column

### ISSUE THREAD

**Issue by kane-mason** [thomas4019/expressa#199]
Not sure if this happens for all dbs, but from what i can tell on the `postgres` update function does not update `id` column when updating `_id`  property, and im sure it should

**Comment by thomas4019** [comment]
Shouldn’t we just use `_id` everywhere? I think I decided it made sense to try and standardize on that since that’s what MongoDB does

**Comment by kane-mason** [comment]
I suppose we could, but i assume there is a performance benefit retrieving the document matching the `id` column rather that searching for _id within the doc? Dont think it would be too hard to update `id` column when updating '_id' either?
