### ISSUE TITLE
listener not triggered on /:collection/:id

### ISSUE THREAD

**Issue by coderofsalvation** [thomas4019/expressa#27]
'/:collection` however, does allow listeners. 
I guess there's a notify missing

**Comment by thomas4019** [comment]
Weird, it's actually working for me so I think this may be something specific to your listener. Can you share the code of the listener?

**Comment by thomas4019** [comment]
Is this still an issue? If not, can I close this bug?

**Comment by coderofsalvation** [comment]
nope..yes..closing :)
