### ISSUE TITLE
Ability to add custom endpoints with expressa request object

### ISSUE THREAD

**Issue by thomas4019** [thomas4019/expressa#31]
I think we need a way to add custom endpoints that also have expressa features like req.user and req.hasPermission so that these custom endpoints can use the current permission model.

**Comment by coderofsalvation** [comment]
we're already doing that I think..

I just do this for adhoc endpoints:

``` expressa.get('/foo/bar',function(req,res,next){.....req.hasPermission....})```

But i agree that does prefix the expressaprefix to the urls..

**Comment by thomas4019** [comment]
Sorry for my late response here. You're right that this can work for adding adhoc endpoints. The only problem I see here is that if the url looks like a standard expressa endpoint then it can try and handle the request and fail. For your given example, expressa would likely think a request coming in with that url would mean accessing the 'bar' document of the 'foo' collection which would fail.

To solve this, I think we need to have an empty router/middleware that we use before adding anyone of the standard express endpoints. Then for adhoc endpoints, the user just needs to add it to that router so it gets the right priority.
