### ISSUE TITLE
error to start

### ISSUE THREAD

**Issue by kimoudev** [thomas4019/expressa#38]
Error: could not load data
    at /var/www/app/node_modules/jfs/lib/Store.js:209:15
    at ReadFileContext.callback (/var/www/app/node_modules/jfs/lib/Store.js:94:16)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:365:13)
j

**Comment by coderofsalvation** [comment]
I've seen this one long time ago.
This might be happening due to a corrupt json (either data/collection/collectionname.js or collection-items data/collectionname/4lkl3k4.json)

**Comment by thomas4019** [comment]
I think this is the error message you get when first starting expressa before going through the installation process. I've changed the error message to be more clear. @kimoudev, can you try upgrading to the latest version and see if it's fixed? Thanks!

**Comment by thomas4019** [comment]
I have improved this error message so I'm going to mark this as closed.
