### ISSUE TITLE
data/settings/development.json...how?

### ISSUE THREAD

**Issue by coderofsalvation** [thomas4019/expressa#39]
Im in the situation where i would like to use data/settings/development.json on my buildserver (without production configvalues).

Any idea how to initialize the development-settings?

Most nodejs applications distinguish between production/development using the NODE_ENV environment flag:

```
if( process.env.NODE_ENV == "production" ){

}else{ // by default nodejs sets it to "development"

}
```

expressa could do something similar, by creating both `development.json` and `production.json` in `data/settings/.` upon first run...and load one based on the NODE_DEV value.

## Example

index.js
```
    28  router.settings = {}
    29
-   30  db.settings.get('production')
+  30  db.settings.get( process.env.NODE_ENV )
    31          .then(function(data) {
    32                  router.settings = data;
```

> NOTE: if this sounds ok let me know, and we'll prepare a PR

**Comment by thomas4019** [comment]
I think this sounds like a great solution! I like the idea of populating both development and production in the installation process. Your modification to index.js looks good. Does NODE_ENV have a default value? If not, let's make sure we have a default.
