### ISSUE TITLE
uncheck anonymous permission for "view users"

### ISSUE THREAD

**Issue by laksh95** [thomas4019/expressa#40]
can you reproduce:
* create an 'users'-collection
* uncheck anonymous permission for "view users"
* do anonymous request to `/api/users` in the browser

We need that the any kind of sensitive information should not be visible to anonymous, authenticated user-role. Only admin role should have access to that.
can you assist in resolving this issue?

**Comment by coderofsalvation** [comment]
true that. something like this should display an empty array:

    $ curl http://localhost:3001/api/users
    []

Can anyone verify this?

**Comment by thomas4019** [comment]
Thanks for reporting this. The issue was that the "view own" permission was broken and letting these through. It should now be fixed if you upgrade to the latest version of expressa.

**Comment by laksh95** [comment]
Thanks for the fix.
