### ISSUE TITLE
copy/pasted payload to jsonschema

### ISSUE THREAD

**Issue by coderofsalvation** [thomas4019/expressa#5]
idea: would be neato to be able to setup collections by :+1: 

* adding an extra 'from payload'-button
* which runs the json payload thru https://www.npmjs.com/package/schemize

**Comment by thomas4019** [comment]
This is a good idea. I think this could exist in the expressa-admin frontend and ideally wouldn't require any backend changes.

**Comment by coderofsalvation** [comment]
moved this to expressa-admin
