### ISSUE TITLE
/users/me returns sensitive data

### ISSUE THREAD

**Issue by coderofsalvation** [thomas4019/expressa#52]
it seems /users/me seems to bypass the listeners (which could hide/delete sensitive properties).

**Comment by thomas4019** [comment]
Hmm, this is unexpected. /user/me is really just a shortcut for /users/:id.

**Comment by thomas4019** [comment]
Any updates here? Can you explain how to reproduce this?

**Comment by coderofsalvation** [comment]
like it returns the password-property here

**Comment by thomas4019** [comment]
Yeah, there's the `hidePasswordHashes` listener for this. There's also the permission `'users: view hashed passwords'` which causes this and other user endpoints return the hashed password so you're probably seeing this issue on an **Admin** account.
