### ISSUE TITLE
adding role resets password?

### ISSUE THREAD

**Issue by coderofsalvation** [thomas4019/expressa#53]
Not totally sure about it, but i noticed a missing password-property.
Im suspecting that adding some roles (thru expressa-admin) caused this.
I'll do some more research.

**Comment by coderofsalvation** [comment]
ok..i think i know what it was...during a PUT request of a user..the password was omitted automatically by the role-middleware.
I found a workaround, but im a bit afraid that my team will be bitten by this again.
Therefore I did a PR, which kindof 'reveals' all kindof magic performed by role-middleware:

https://github.com/thomas4019/expressa/pull/54

**Comment by thomas4019** [comment]
Ohh, that makes sense. For safety reasons I think it makes sense to omit the password, but I see now I have a pending TODO about this issue. So far, the approach I've been using for user updates is to POST to 'users/:id/update' with the following data. 
```
var data = {
            $set: this.data,
            $unset: {'permissions': true}
          }
```
