### ISSUE TITLE
/:collection/:id/update seems unimplemented

### ISSUE THREAD

**Issue by coderofsalvation** [thomas4019/expressa#56]
I tried updating some isolated properties of an object.
However, looking at the code it seems unfinished no?

the 'changed'-variable seems unused in `router.post('/:collection/:id/update', > (req, res, next) {` in `index.js`

**Comment by thomas4019** [comment]
Yeah, this is a bit unclear. The mongoQuery function mutates the doc. The changes is not important and unused currently so there's no reason to store it. That said, /:collection/:id/update is working currently.
