### ISSUE TITLE
possible security leak

### ISSUE THREAD

**Issue by coderofsalvation** [thomas4019/expressa#57]
![screenshot 2017-08-04 at 10 07 28](https://user-images.githubusercontent.com/180068/28959923-dc7eb39c-78fc-11e7-81c8-8a2f06eb9ac6.png)

not sure, but maybe this allows users with 'edit own: true'-permissions to overwrite non-owned collection-items by sending a PUT request with a modified `{.....,meta:{owner:'hackeruid'}}`

In the case of updating items, we might want expressa to retrieve the collection-item first from the db, so we'll know for sure we're dealing with a legit owner-property.

**Comment by thomas4019** [comment]
Thanks for finding this big issue. We are already retrieving the existing item from the db so for now I've done a small change to make it run the listeners with the old owner and only update the owner after getting approval. This allows admins to change any owner and existing owners to transfer ownership. I'm going to mark this as closed, but if you think of any problems with this fix, feel free to reopen.
