### ISSUE TITLE
database adapter consistency

### ISSUE THREAD

**Issue by coderofsalvation** [thomas4019/expressa#60]
Hi,

I had to migrate file-collections to postgres using expressa-cli, and found out all my tests failed.

## REASON

It turns out all the database adapters return an id after a create() db-call, except postgres returns an object.
I introduced an environment-flag to not cause harm for existing postgres expressa-users for now.
However, I do believe we want to make this default behaviour, so we could, at somepoint bump the versionnumber to indicate a breaking change for postgres users (v0.4.x etc).

**Comment by thomas4019** [comment]
I'm sorry about this inconsistency. Thanks for the fix! I think making the breaking change in the next version makes sense since there's a few others like the pagination fix as well.

**Comment by thomas4019** [comment]
I've made Postgres work like the others and added tests to make sure all database implementations conform to the same interface. :)
