### ISSUE TITLE
Initial admin startup

### ISSUE THREAD

**Issue by ArneOb** [thomas4019/expressa#61]
Hi,
from your readme I would have expected to have a login. But there are no credentials mentioned. So I fail attempting to get through the admin UI. Any help appreciated!

**Comment by thomas4019** [comment]
Hi Arne,
Did you got through the install process? When visiting http://localhost:3000/admin for the first time, it should redirect you to http://localhost:8080/admin/#/install. On that form you create an administration account with an email and password.
Let me know if that helps. If not, can you check if you have a file at data/settings/development.json in your project? Any other info you can provide can help too. Thanks!

**Comment by NMonst4** [comment]
Same here no redirect by your installation instructions

**Comment by thomas4019** [comment]
Hi, thanks for your feedback. It turns out there's an error in the example app.js and I've just fixed it. The line for the admin should include the apiurl like the line below.
```app.use('/admin', expressa.admin({ apiurl: '/api/' }));```
Let me know if this works for you.

**Comment by pantchox** [comment]
it showed the initial admin install process for me! 
this project looks great!

**Comment by thomas4019** [comment]
Thanks for letting me know!
