### ISSUE TITLE
relationships example not working for me

### ISSUE THREAD

**Issue by j2l** [thomas4019/expressa#65]
I tried following https://github.com/thomas4019/expressa/blob/master/doc/relationships.md but didn't get expected results.
Is this property in meta? Or declared as object in root, then additional properties in root?
Do we need to change additionalProperties to true?

Thanks!

**Comment by thomas4019** [comment]
The properties is generally at the root level of a collection schema. It is easiest to modify an existing collection schema and add links there. You just need to add a links field on the relevant fields inside your properties. See [this gist](https://gist.github.com/thomas4019/b428bb93ffeee434a016db7f64553e5f) for a full collection schema with some links.

additionalProperties is an unrelated json schema property which means that expressa should allow keys not explicitly listed to be saved and returned as well.  I hope this helps.

**Comment by j2l** [comment]
Thanks! It works now.
Weird because I tried that initially. May be some character was not correctly escaped when pasting in the json file.
BTW, I would have liked to use the inline JSON editor (which is great!) but it discards the links and jump right to the next object (meta):
![image](https://user-images.githubusercontent.com/65325/45609406-2c6c8d00-ba58-11e8-9654-a3a86b9745d3.png)
Coming from graphcool (which is way too hard to escape request strings in C#, it works but it's really tedious), I'd love to see a full working relational set in expressa 😄

**Comment by thomas4019** [comment]
Glad it's working for you! I agree it would be nice for relationships to work in the JSON editor. Unfortunately, they're not part of the schema currently so they get removed by it.
