### ISSUE TITLE
TypeError: expressa.addListener is not a function

### ISSUE THREAD

**Issue by j2l** [thomas4019/expressa#66]
Still trying to make something 😸 
I don't get why it throw that since addListener is present in listerner.js.
Here's the beginning of server.js:
```
var express = require('express');
var app = express();
var expressa = require('expressa');
app.use(express.static('public'));
app.use('/api', expressa.api());            // optionally pass in settings
app.use('/admin', expressa.admin({ apiurl: '/api/', showCriticalFeaturesOnProduction: true }));
app.get('/', function(request, response) {
  response.sendFile(__dirname + '/views/index.html');
});
expressa.addListener('get', -101, function (req, collection, doc) {
...
```

**Comment by j2l** [comment]
Thanks Thomas! 
But now I get 2 errors:
```
bundle.js:40043 GET https://xxxx/api/users/schema 500 ()
xhrAdapter @ bundle.js:40043
executor @ bundle.js:101950
dispatchRequest @ bundle.js:101934
Promise.then (async)
request @ bundle.js:101796
Axios.(anonymous function) @ bundle.js:101825
wrap @ bundle.js:102394
doGet @ bundle.js:8129
componentDidMount @ bundle.js:114229
chainedFunction @ bundle.js:28270
(anonymous) @ bundle.js:72129
measureLifeCyclePerf @ bundle.js:71940
(anonymous) @ bundle.js:72128
notifyAll @ bundle.js:28770
close @ bundle.js:74042
closeAll @ bundle.js:15694
perform @ bundle.js:15641
perform @ bundle.js:15628
perform @ bundle.js:8291
flushBatchedUpdates @ bundle.js:8374
closeAll @ bundle.js:15694
perform @ bundle.js:15641
batchedUpdates @ bundle.js:73752
batchedUpdates @ bundle.js:8299
dispatchEvent @ bundle.js:73910
/admin/#/collection/users?_k=1n1xb0:1 Uncaught (in promise) {data: {…}, status: 500, statusText: "", headers: {…}, config: {…}, …}
```
What could help you find new devs and could help debug, is a full working server at glitch.com (free). I can PM you my half-baked server, if it helps 😄 but I'm not related to glitch.com at all.

**Comment by thomas4019** [comment]
Hi,
I think this is an issue with your listener code. For this, I think I'd need to see your listener code to know what's wrong. Your listener code should get 3 arguments _req, collection, data_. It's probably _data_ that you're wanting to use, but you may want to only run code when it's a notification for a certain collection.

I've never seen glitch.com before, but it does look useful. Please do email me your example so I can look at putting up a full example. Thanks for the idea.

**Comment by j2l** [comment]
The listener is the stock one from your [relationships example](https://github.com/thomas4019/expressa/blob/master/doc/relationships.md).
Here's [my link](https://glitch.com/edit/#!/expressatest), not sure if you can edit or ask for editing the project. Let me know.

**Comment by thomas4019** [comment]
It looks like the listener is failing here because of the handler code. When doing database lookups you need to access the user table on the expressaAPI instance returned by expressa.api(). expressa.db.users will fail because db is not defined on the root object.
