### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by shubhendusaurabh** [thomas4019/expressa#69]
after installing via npm and adding necessary code changes, when I go to http://localhost:3000/admin/ i am redirected to install page but when I try to save changes, i get error.

![error](https://user-images.githubusercontent.com/1818387/64820587-56568200-d5ce-11e9-99fe-f4c15320dc59.png)

there is no data/settings/development.json file being created.

Any help would be appreciated.

**Comment by thomas4019** [comment]
Hi @shubhendusaurabh, sorry for the delay. Are you putting in an email and password for the "administrator account". Also, can you send add a screenshot of the install page? Thanks!

**Comment by shubhendusaurabh** [comment]
@thomas4019 Yes, i did. 

![expres](https://user-images.githubusercontent.com/1818387/65378667-74f8ff00-dcd9-11e9-8161-6022b58ee9b9.png)

in my express logs I'm getting following error:

`
error in listener
TypeError: Cannot read property 'find' of undefined
    at allowFirstAdmin (/home/shubhu/dev/projectx/node_modules/expressa/listeners.js:159:25)
    at /home/shubhu/dev/projectx/node_modules/expressa/index.js:223:18
    at /home/shubhu/dev/projectx/node_modules/promise-sequential/index.js:16:18
`

**Comment by thomas4019** [comment]
Hi,
Thanks for the logs. I've pushed a fix to npm as 0.4.5. If you clear the data folder in your project and try installing again it should now work. I'm not sure why I wasn't able to reproduce this earlier. Thanks for your help.
