### ISSUE TITLE
Error on install if 'users' initial storage type set as 'postgresql'

### ISSUE THREAD

**Issue by kane-mason** [thomas4019/expressa#78]
Hi, 

I am following the instructions on the README to get a simple server and database set up. I have the following file server.js

`
var express = require('express');
var app = express();

var expressa = require('expressa');
app.use('/api', expressa.api());            // optionally pass in settings
app.use('/admin', expressa.admin({ apiurl: '/api/' }));

app.listen(3000, function () {
    console.log('Example app listening on port 3000!');
});`

I have created an empty database 'test' in pgAdmin

![image](https://user-images.githubusercontent.com/23186829/81609701-a1809900-93d8-11ea-8991-5523d11b13ee.png)

I run my server, and navigate to localhost:3000/admin

![image](https://user-images.githubusercontent.com/23186829/81609863-e278ad80-93d8-11ea-8e5a-9fb427409188.png)

But when i click i get the following error(s):

![image](https://user-images.githubusercontent.com/23186829/81610264-85c9c280-93d9-11ea-99dd-b91738f55d35.png)

I am on a laptop using windows 10

Thanks

**Comment by thomas4019** [comment]
Thanks for the detailed instructions. I was able to replicate this issue and I pushed a fix in version `0.4.6`. Can you try installing the latest version of expressa and see if it works now? Thanks!

**Comment by kane-mason** [comment]
Thanks for the prompt response. I have updated but still seem to getting the same (or similar) issue? The post request `http://localhost:3000/api/users` in devtools fails with Internal Server Error and the following in the server console.

![image](https://user-images.githubusercontent.com/23186829/81735888-08b05300-9496-11ea-9a48-a6a4557c49ca.png)


I wondered if it had anything to do with adding the port, still errors with slightly different error, and the user post request doesn't fail, it hangs.

![image](https://user-images.githubusercontent.com/23186829/81735668-ae16f700-9495-11ea-821a-ed46c718d2bd.png)

![image](https://user-images.githubusercontent.com/23186829/81735622-9a6b9080-9495-11ea-8927-70693dcfe96f.png)

**Comment by thomas4019** [comment]
This should now be fixed with the new install process released in version 0.5.0

**Comment by kane-mason** [comment]
working thanks
