### ISSUE TITLE
Api SQL Queries

### ISSUE THREAD

**Issue by kane-mason** [thomas4019/expressa#79]
Hi,

In the documentation it says we are able to execute queries on a collection via the api: 

`/:collection/?query={..}`

Where the query has to be in the form of a mongo-query. If my databse is jsonb postgres can i execute jsonb sql queries?

**Comment by thomas4019** [comment]
Hi Kane,
Yes, this works even if you're using a postgres database, because it uses [this library](https://github.com/thomas4019/mongo-query-to-postgres-jsonb) to map it to a jsonb query. There are corner cases of course, but the vast majority of features are covered.

**Comment by kane-mason** [comment]
Thomas, sorry i don't think i explained myself well enough. 

I meant if you wanted to write the query in jsonb sql format as opposed to a mono-query format. For example:

users/?query={data->>'email'='myemail@me.com'}

I have tried but getting an error, so not sure if my syntax is wrong or it is just not supported as yet. If not supported might be a cool feature for those who don't want to deal with mongo queries:)

**Comment by thomas4019** [comment]
Ahh, that makes sense. I'll take this into consideration.

A nice thing with Mongo queries is that they're supported for all 3 supported database types (Mongo, Postgres and In-memory) and since they're JSON they're easily automatically generated.

**Comment by kane-mason** [comment]
Ah yes i didn't fully consider the other database types. Would still be a nice-to-have feature request for me! Thanks for the response
