### ISSUE TITLE
Unable to access admin page after update to 0.5.0

### ISSUE THREAD

**Issue by kane-mason** [thomas4019/expressa#80]
Hi,

I updated my test app to 0.5.0.

I followed the exact steps in the readme but am unable to reach the admin page.

server.js
![image](https://user-images.githubusercontent.com/23186829/84936057-f307fc00-b0d9-11ea-8ca2-2f7b634d6b9f.png)

error in chrome
![image](https://user-images.githubusercontent.com/23186829/84936174-25b1f480-b0da-11ea-99ef-fbe51f89bef8.png)

console
![image](https://user-images.githubusercontent.com/23186829/84936242-45e1b380-b0da-11ea-9a85-39bf40ebffd4.png)

node 10.20.1

**Comment by thomas4019** [comment]
Hi Kane, thanks for filing this ticket. Since this was the first release with the new admin UI, I didn't realize that I needed to change how it got published to NPM. Should be fixed now with version 0.5.1.

**Comment by kane-mason** [comment]
working thanks!
