### ISSUE TITLE
Super user details not persisted into database after setup

### ISSUE THREAD

**Issue by kane-mason** [thomas4019/expressa#81]
Using the new admin interface i setup a database with the users storage set to 'postgres'. And the set up succeeds but it seems the default username and password (a@example.com and 123) are what is carried into the database, and not the values i entered in the setup page

![image](https://user-images.githubusercontent.com/23186829/84941383-9d375200-b0e1-11ea-8f45-7376da8133af.png)

**Comment by thomas4019** [comment]
Good catch! Fixed and released in version `0.5.2`
