### ISSUE TITLE
Potential Permissions Problem

### ISSUE THREAD

**Issue by kane-mason** [thomas4019/expressa#83]
Hi,

So i installed a server and created an admin user. Then, logged in as that admin user in the /admin page, i created a new user with the predefined `Authenticated` role. I then logged out of the super user, and back in as the new 'Authenticated' user, and was still able to do everything i did as an admin user, creating collections, adding users etc. Is this correct? I was thinking because the Authenticated role only has these limited `{ "users: view own": true, "users: edit own": true, "users: delete own": true }` permissions, that i shouldn't be able to?

**Comment by thomas4019** [comment]
Thanks! This is a big issue. There's a permission called "enforce_permissions" which needs to be set to **true** for them to actually be enforced and the new admin install process wasn't setting that. I'm looking into making this permission implicitly true in the next release, but for now the install process is fixed so it correctly sets the value in 0.5.3.

**Comment by kane-mason** [comment]
Thanks, this seems to be working. However it still allows the user to login via the /admin route. Is there a way to restrict access entirely to the admin page if the user does not have an admin role (or some other way, maybe an extra permission) ?

**Comment by thomas4019** [comment]
I created a new permissions `login to admin`. The `Admin` user will get this role automatically and now only users with that role can log into the Admin panel.
