### ISSUE TITLE
Expose pg pool (or just pool.query) on db object

### ISSUE THREAD

**Issue by kane-mason** [thomas4019/expressa#87]
For those who want to execute custom queries etc on the database, it would be better if the request was made from the existing Pool already created within expressa. The alternative is requiring pg in your project and creating another pool/connection which to me is inefficient and bypasses the contract between your server and expressa. I think all comms should happen via expressa.

Small side note -> i noticed you create a pool per collection, which could result in quite a few pools depending on application, and the documentation recommends limited number, even just 1: https://node-postgres.com/features/pooling

**Comment by thomas4019** [comment]
Good idea. I've exposed the pool object. I think using a single pool does make sense across all collections, but not sure how to best do that yet. Let's leave this open until that's done.

**Comment by kane-mason** [comment]
I see your dilemna, maybe if you could figure out a neat way to create and expose the pool in the `api.db` layer, rather than the collection layer it could be injected and shared between collections

**Comment by kane-mason** [comment]
#99 resolves this
