### ISSUE TITLE
Suggestion: Limit api.db.users.find() in allowFirstUserAsAdmin

### ISSUE THREAD

**Issue by kane-mason** [thomas4019/expressa#88]
I was thinking it might be wise to limit the below call in `allowFirstUserAsAdmin` to top 1 result. Since it happens for every post query on the users collection it might be called frequently, theoretically getting worse as a site gets more users. Also as more users get added the json payload grows, and we just need a count.

`const userCount = (await api.db.users.find()).length`

I am not a mongo query expert but from some googling it seems this may be achievable with `{ $limit : 1 }`

**Comment by thomas4019** [comment]
This is a great idea since the current implementation really is very inefficient. I'll make it only pull one like you suggest.
