### ISSUE TITLE
Possible Document Owner Bug

### ISSUE THREAD

**Issue by kane-mason** [thomas4019/expressa#89]
I have a user who could not edit their own document in another collection despite having the correct editown permission. I noticed the documents owners were coming in as `undefined` and i believe it is tracked down to the following:

In `collections.js` line 127

`const owner = doc.owner && doc.meta.owner`

Maybe supposed to be

`const owner = doc.meta && doc.meta.owner`

?

**Comment by kane-mason** [comment]
Actually having another look at the code my proposed solution may not be correct, but i think the issue is related and does lie in the surrounding areas. 

Basically `doc.meta.owner` is being overwritten as `undefined`

**Comment by thomas4019** [comment]
Thanks for reporting this! There was a definite typo there and also an issue where the owner wasn't be recorded if documents were created via a PUT. I've fixed both and added some tests.
