### ISSUE TITLE
BlueBird

### ISSUE THREAD

**Issue by kane-mason** [thomas4019/expressa#92]
In the era of node >= 10 is it necessary to use BlueBird? 

Since native promises have come a long way, I don't see any of Bluebirds special features being used so could now be a good time to reconsider? 

My other concern is expressa overwrites the global.Promise giving no way for the consumer to choose native promises themselves.

**Comment by thomas4019** [comment]
Hmm, one of the major features of Bluebird that I had included it for is [long stack traces](http://bluebirdjs.com/docs/api/promise.longstacktraces.html). Luckily though with Node 12 these are now native and much more performant [(see here)](https://thecodebarbarian.com/async-stack-traces-in-node-js-12) so I agree it's no longer necessary. I'll remove it as a dependency in the next release.

**Comment by thomas4019** [comment]
Bluebird was removed in release `0.5.6` :)
