### ISSUE TITLE
Schemas not displaying correctly

### ISSUE THREAD

**Issue by kane-mason** [thomas4019/expressa#98]
When viewing a schema, the properties are not visible. See below screenshot when viewing the 'users' collection schema.

Where is email? fullName? etc etc

![image](https://user-images.githubusercontent.com/23186829/90383034-e410dc00-e07f-11ea-90aa-7f95242b75b5.png)

**Comment by thomas4019** [comment]
Thanks for bringing this up. This was a regression from my prior schema editor change. Should be fixed now.

**Comment by kane-mason** [comment]
Confirmed fixed
